### PR TITLE
Added typesafe addXyzChecker() methods for built-in checkers

### PR DESCRIPTION
**Pull request by rgoldberg**
Added typesafe `addXyzChecker()` methods for built-in checkers

### CODE REVIEW

**Comment by mernst** [comment]
The documentation claims that if no processors are added, the Nullness Checker is run.  The behavior of running no checker is better, but should be documented.

**Comment by rgoldberg** [comment]
Somehow, the wrong comment was added to this PR. The same comment is correctly in my other PR #4.

**Comment by mernst** [comment]
@rgoldberg Sorry for my mixing up the pull requests, and thanks for fixing it.

**Comment by rgoldberg** [comment]
No problem. It was my fault for putting the wrong initial comment in this PR anyway, so it would have been easy for anyone to mix them up.

About this PR: are there any other built-in checkers for which I should add methods?

**Comment by mernst** [comment]
It's a bit odd to include the Initialization Checker but not the Map Key Checker.  Both are implementation details of the Nullness Checker.

I would include the [Subtyping Checker](https://checkerframework.org/manual/#subtyping-checker).

I noticed that the Aliasing Checker and Constant Value Checker are also missing.

I noticed that the Purity Checker is missing from both your list and the Checker Framework Manual (!).

**Comment by mernst** [comment]
@rgoldberg There is a merge conflict in this pull request.  Could you please resolve it?

**Comment by rgoldberg** [comment]
I don’t know the new codebase, and I’m sorta busy now.

The concept of non-literal String arguments should be straightforward, though. Either make a string constant for each built-in checker, or add a method to add each. Given the new API, String constants probably make more sense.

Obviously, using String literals is bad because it’s error prone, and will only be discovered at runtime.

**Comment by mernst** [comment]
@rgoldberg Sounds good.  I opened a feature request, #10, for this.  Please chime in there if it doesn't capture your idea.
It should be easy to implement.
Thanks!

**Pull request closed without merging**
